name = "ada_lua"
description = "An Ada binding for lua"
version = "0.1.0"
authors = ["Nicolas Roche <roche@adacore.com>"]
maintainers = ["Nicolas Roche <roche@adacore.com>"]
maintainers-logins = ["Nikokrock", "Fabien-Chouteau"]
website = "https://github.com/adacore/ada-lua"
licenses = ["GMGPL 3.0"]
tags = ["lua", "binding", "script"]
 
[[depends-on]]
liblua = "~5.3"
